name: crobros
description: "A new Flutter project."

publish_to: "none"

# version
version: 1.0.0+1

# environment
environment:
  sdk: ^3.8.1

# dependencies
dependencies:
  cloud_firestore: ^5.6.10
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.6.1
  firebase_core: ^3.15.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  get: ^4.7.2
  get_storage: ^2.1.1
  google_sign_in: ^7.1.0
  http: ^1.4.0
  intl: ^0.20.2
  logger: ^2.6.0
  smooth_page_indicator: ^1.2.1
  url_launcher: ^6.3.1

# development dependencies
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

# flutter_native_splash
flutter_native_splash:
  color: "#ffffff"
  color_dark: "#272727"
  image: assets\logos\light.png
  image_dark: assets\logos\dark.png

  android_12:
    color: "#ffffff"
    color_dark: "#272727"
    image: assets\logos\light.png
    image_dark: assets\logos\dark.png

  web: false

flutter:
  # assets:
  assets:
    - assets/icons/
    - assets/images/
    - assets/logos/
    - assets/images/onboarding_images/
  # fonts:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #         weight: 400
  #       - asset: fonts/Schyler-Italic.ttf
  #         weight: 400
  #         style: italic
