// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNmKMpIksHwlzz5tqCQK4cYcpb2dhIL5s',
    appId: '1:281848962603:web:e12e538ac2b595b937d46e',
    messagingSenderId: '281848962603',
    projectId: 'crobros-63f84',
    authDomain: 'crobros-63f84.firebaseapp.com',
    storageBucket: 'crobros-63f84.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuUZlU7MtGQYdk3F3iuHwbI9VdqLIgmrI',
    appId: '1:281848962603:android:55bb5953c50a107837d46e',
    messagingSenderId: '281848962603',
    projectId: 'crobros-63f84',
    storageBucket: 'crobros-63f84.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdjeoXOEB-FxZ_yVksLRIY0l-l2qaLWNs',
    appId: '1:281848962603:ios:278200b0b2d6fe4337d46e',
    messagingSenderId: '281848962603',
    projectId: 'crobros-63f84',
    storageBucket: 'crobros-63f84.firebasestorage.app',
    iosClientId: '281848962603-s7clf77n27gbt01htcukfci0d5rnhe5e.apps.googleusercontent.com',
    iosBundleId: 'com.example.crobros',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdjeoXOEB-FxZ_yVksLRIY0l-l2qaLWNs',
    appId: '1:281848962603:ios:278200b0b2d6fe4337d46e',
    messagingSenderId: '281848962603',
    projectId: 'crobros-63f84',
    storageBucket: 'crobros-63f84.firebasestorage.app',
    iosClientId: '281848962603-s7clf77n27gbt01htcukfci0d5rnhe5e.apps.googleusercontent.com',
    iosBundleId: 'com.example.crobros',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNmKMpIksHwlzz5tqCQK4cYcpb2dhIL5s',
    appId: '1:281848962603:web:5daf09fa61e366ff37d46e',
    messagingSenderId: '281848962603',
    projectId: 'crobros-63f84',
    authDomain: 'crobros-63f84.firebaseapp.com',
    storageBucket: 'crobros-63f84.firebasestorage.app',
  );

}